### PR TITLE
Prm 3184 added pay now url and routing

### PR DESCRIPTION
**Pull request by RoheelArshad**

### CODE REVIEW

**Review by JBlacklaws — CHANGES_REQUESTED** [review]
LGTM

I investigated the services we can run, if we run PAY_API and PAY_FRONTEND the we can test this link working locally. May be worth adding to PENALTIES_ALL services_config, as we did with ESSTTP

**Comment by RoheelArshad** [comment]
build

**Comment by RoheelArshad** [comment]
test

**Comment by RoheelArshad** [comment]
test this please

**Review by JBlacklaws — APPROVED** [review]

**Pull request merged**
