### PR TITLE
PRM-2925 removed javascript for duplicate uploads

### PR DESCRIPTION
**Pull request by RoheelArshad**

### CODE REVIEW

**Review by LewisMitchell — CHANGES_REQUESTED** [review]
https://github.com/hmrc/penalties-appeals-frontend/blob/8ee85f4a41c97e353d78c539dc5a4b6a9b1a3c7c/app/assets/javascripts/upload/multiFileUpload.js#L36 can be removed
https://github.com/hmrc/penalties-appeals-frontend/blob/8ee85f4a41c97e353d78c539dc5a4b6a9b1a3c7c/app/assets/javascripts/upload/multiFileUpload.js#L216 can be removed
https://github.com/hmrc/penalties-appeals-frontend/blob/8ee85f4a41c97e353d78c539dc5a4b6a9b1a3c7c/app/assets/javascripts/upload/multiFileUpload.js#L707 can be removed
https://github.com/hmrc/penalties-appeals-frontend/blob/8ee85f4a41c97e353d78c539dc5a4b6a9b1a3c7c/app/assets/javascripts/upload/multiFileUpload.js#L859-L865 can be removed
https://github.com/hmrc/penalties-appeals-frontend/blob/8ee85f4a41c97e353d78c539dc5a4b6a9b1a3c7c/app/assets/javascripts/upload/multiFileUpload.js#L868-L870 can be removed

**Comment by RoheelArshad** [comment]
made changes now

**Comment by LewisMitchell** [comment]
Looks like the tests are failing, they should be verifiable locally with: `sbt test`

**Comment by LewisMitchell** [comment]
rebuild

**Comment by RoheelArshad** [comment]
I think all comments are resolved and tests pass now

**Review by LewisMitchell — APPROVED** [review]
Rebased locally and everything works as expected

**Pull request merged**
