### PR TITLE
[PRM-877] - Create audit model and send audit when duplicates exist

### PR DESCRIPTION
**Pull request by LewisMitchell**

### CODE REVIEW

**Comment by LewisMitchell** [comment]
Trader:
```
{
    "auditSource": "penalties-appeals-frontend",
    "auditType": "PenaltyDuplicateFilesSubmitted",
    "eventId": "ea6f96b8-69b7-4d97-91a8-650130d4d58e",
    "tags":
    {
        "clientIP": "-",
        "path": "/penalties-appeals/check-your-answers",
        "X-Session-ID": "session-a6b06028-5503-4c9e-8db4-9f374c043bbc",
        "Akamai-Reputation": "-",
        "X-Request-ID": "govuk-tax-1b0f6695-3778-481f-9b5b-d2a16de25a3a",
        "deviceID": "mdtpdi#c90c2cfd-2c2e-4fee-abe2-fe46edfd868e#1638179382535_OCCVOkzFDow9n8meekWFGw==",
        "clientPort": "-",
        "transactionName": "penalties-duplicate-files-submitted"
    },
    "detail":
    {
        "submittedBy": "client",
        "taxIdentifier": "224060020",
        "identifierType": "VRN",
        "duplicateFiles":
        [
            {
                "upscanReference": "f54b1980-8237-46c1-9649-d3e133de8889",
                "uploadTimestamp": "2021-12-08T11:24:19.114",
                "name": "1-duplicate.png",
                "mimeType": "image/png",
                "size": 236624,
                "checksum": "75aebcc7ef45f5a7b18f7e2ff24ea9ba4c50755c2d1677c5f1c291496855dda0"
            },
            {
                "upscanReference": "d373b306-f605-4fc9-8d4e-ee660d025b8b",
                "uploadTimestamp": "2021-12-08T11:24:21.268",
                "name": "1-duplicate.png",
                "mimeType": "image/png",
                "size": 236624,
                "checksum": "75aebcc7ef45f5a7b18f7e2ff24ea9ba4c50755c2d1677c5f1c291496855dda0"
            }
        ]
    },
    "generatedAt": "2021-12-08T11:24:38.618+0000",
    "metadata":
    {
        "sendAttemptAt": "2021-12-08T11:24:38.618+0000",
        "instanceID": "8dde26ab-003e-45cc-832b-f9c9a4764679",
        "sequence": 53
    }
}
```

**Comment by LewisMitchell** [comment]
Agent:
```
{
    "auditSource": "penalties-appeals-frontend",
    "auditType": "PenaltyDuplicateFilesSubmitted",
    "eventId": "2bdaf21c-f88e-4d94-ac63-aad14d34398f",
    "tags":
    {
        "clientIP": "-",
        "path": "/penalties-appeals/check-your-answers",
        "X-Session-ID": "session-9cf4cad3-1764-499f-b9a2-4a82d25b7ab1",
        "Akamai-Reputation": "-",
        "X-Request-ID": "govuk-tax-11b541e8-46b0-4076-b72b-0637fefe9cf0",
        "deviceID": "mdtpdi#c90c2cfd-2c2e-4fee-abe2-fe46edfd868e#1638179382535_OCCVOkzFDow9n8meekWFGw==",
        "clientPort": "-",
        "transactionName": "penalties-duplicate-files-submitted"
    },
    "detail":
    {
        "submittedBy": "agent",
        "taxIdentifier": "224060020",
        "identifierType": "VRN",
        "agentReferenceNumber": "123456789",
        "duplicateFiles":
        [
            {
                "upscanReference": "3a847ee1-032a-42f2-a313-fdda8d38e429",
                "uploadTimestamp": "2021-12-08T11:26:25.198",
                "name": "1-duplicate.png",
                "mimeType": "image/png",
                "size": 236624,
                "checksum": "75aebcc7ef45f5a7b18f7e2ff24ea9ba4c50755c2d1677c5f1c291496855dda0"
            },
            {
                "upscanReference": "183a5e6a-43d5-43dd-bd9d-5253eef29401",
                "uploadTimestamp": "2021-12-08T11:26:27.155",
                "name": "1-duplicate.png",
                "mimeType": "image/png",
                "size": 236624,
                "checksum": "75aebcc7ef45f5a7b18f7e2ff24ea9ba4c50755c2d1677c5f1c291496855dda0"
            }
        ]
    },
    "generatedAt": "2021-12-08T11:26:41.943+0000",
    "metadata":
    {
        "sendAttemptAt": "2021-12-08T11:26:41.943+0000",
        "instanceID": "8dde26ab-003e-45cc-832b-f9c9a4764679",
        "sequence": 154
    }
}
```

**Comment by LewisMitchell** [comment]
For:
image

**Review by JBlacklaws — APPROVED** [review]
LGTM

**Pull request merged**
