### PR TITLE
[PRM-1329]: updated HealthAppealInfo to include only required data

### PR DESCRIPTION
**Pull request by BackRowOla**

### CODE REVIEW

**Review by LewisMitchell — CHANGES_REQUESTED** [review]
Looks good, I was wondering if we could remove the hospitalStayInvolved parameter. If we still receive it by the appeals service then that's OK

**Comment by LewisMitchell** [comment]
Also this requires a backend PR

**Comment by BackRowOla** [comment]
> Also this requires a backend PR

I'll add another subtask to the [ticket](https://jira.tools.tax.service.gov.uk/browse/PRM-1315)

**Comment by BackRowOla** [comment]
> Looks good, I was wondering if we could remove the hospitalStayInvolved parameter.

As in remove this [line](https://github.com/hmrc/penalties-appeals-frontend/blob/79b53d0c66a67785a28177f9dba7b8aa6e6aba8f/app/models/appeals/AppealSubmission.scala#L281)?

**Comment by LewisMitchell** [comment]
> > Looks good, I was wondering if we could remove the hospitalStayInvolved parameter.
> 
> As in remove this [line](https://github.com/hmrc/penalties-appeals-frontend/blob/79b53d0c66a67785a28177f9dba7b8aa6e6aba8f/app/models/appeals/AppealSubmission.scala#L281)?

Yeah

**Comment by BackRowOla** [comment]
> > > Looks good, I was wondering if we could remove the hospitalStayInvolved parameter.
> > 
> > 
> > As in remove this [line](https://github.com/hmrc/penalties-appeals-frontend/blob/79b53d0c66a67785a28177f9dba7b8aa6e6aba8f/app/models/appeals/AppealSubmission.scala#L281)?
> 
> Yeah

It's still being used over [here](https://github.com/hmrc/penalties-appeals-frontend/pull/308/files#diff-7c0812bf1f4320b79b618b32f8caa3302bb0926ce2e3661c1dc768abf7d93153R326)

**Comment by LewisMitchell** [comment]
> > > > Looks good, I was wondering if we could remove the hospitalStayInvolved parameter.
> > > 
> > > 
> > > As in remove this [line](https://github.com/hmrc/penalties-appeals-frontend/blob/79b53d0c66a67785a28177f9dba7b8aa6e6aba8f/app/models/appeals/AppealSubmission.scala#L281)?
> > 
> > 
> > Yeah
> 
> It's still being used over [here](https://github.com/hmrc/penalties-appeals-frontend/pull/308/files#diff-7c0812bf1f4320b79b618b32f8caa3302bb0926ce2e3661c1dc768abf7d93153R326)

Sorry! Looks to be used, once the backend PR is ready I'll look at it as a whole

**Pull request closed without merging**
