### PR TITLE
PRM-2520 added new CSP to our service

### PR DESCRIPTION
**Pull request by RoheelArshad**

### CODE REVIEW

**Comment by AndrewRButcher** [comment]
Couple of issues I have noticed
1. JS code shown above GOVUK banner
Screenshot 2023-04-27 at 10 59 04
2. File upload doesn't seem to be functioning (JavaScript not loading correctly)
Screenshot 2023-04-27 at 11 01 29

**Comment by RoheelArshad** [comment]
@AndrewRButcher Fixed the if syntax.
File upload problem you shown is also on Main branch

**Comment by AndrewRButcher** [comment]
Ok taking another look now File upload was not working on first attempt to review seems fine now will continue with review

**Review by AndrewRButcher — DISMISSED** [review]
Changes approved although waiting on AT update before merging

**Comment by RoheelArshad** [comment]
Rebuild

**Comment by RoheelArshad** [comment]
Rebuild

**Review by AndrewRButcher — APPROVED** [review]

**Pull request merged**
