### PR TITLE
[PRM-1588] - Use Mongo for storing and retrieving session data

### PR DESCRIPTION
**Pull request by LewisMitchell**
PR worked on by Jack and Andrew also

### CODE REVIEW

**Comment by LewisMitchell** [comment]
test this please

**Review by ruthdas03 — COMMENTED** [review]
Couple of observations.
The session data stored in the repository doesn't get deleted from the repository after the user logs out (which happens when we store data in sessions).  This would result in need of purging the collection.

Also there seems to be a bug in CYA 'health-reason' appeal flow which may not be related to the changes made in this pr

https://user-images.githubusercontent.com/86231805/183359690-f52b9e3a-a17a-4928-ac27-31cc54fadda9.mov

**Review by ruthdas03 — CHANGES_REQUESTED** [review]
Please resolve conflicts.

**Comment by LewisMitchell** [comment]
> Couple of observations. The session data stored in the repository doesn't get deleted from the repository after the user logs out (which happens when we store data in sessions). This would result in need of purging the collection.
> 
> Also there seems to be a bug in CYA 'health-reason' appeal flow which may not be related to the changes made in this pr
> 
>  Screen.Recording.2022-08-05.at.16.55.44.mov

So the issue is being caused by incomplete session data, because you (the user) has selected that a hospital stay was not required and then didn't complete the rest of the data required for that flow when you try to go back to the CYA page, it doesn't have all the data it needs.

**Comment by LewisMitchell** [comment]
The data expires after X amount of time anyway, if you want me to add the purging in, I can do that?

**Comment by ruthdas03** [comment]
> The data expires after X amount of time anyway, if you want me to add the purging in, I can do that?

Ok so we are using native Mongo functionality to expire the record after 1 hour.

**Review by ruthdas03 — APPROVED** [review]

**Pull request merged**
